### ISSUE TITLE
What is `detailed_prop`?

### ISSUE THREAD

**Issue by bsuwal** [uscensusbureau/census2020-das-2010ddp#11]
In the config file, there is a field named `detailed_prop` , what does it do, and what is it used for?

https://github.com/uscensusbureau/census2020-das-2010ddp/blob/058d8daf07463c6d3d079036c945271af55d1fa6/das_decennial/configs/census_1940/ipums_1940.ini#L195

**Comment by garfi303** [comment]
In operation, the DAS uses differentially private primitives to take noisy measurements of a number of queries. Most of these queries are handled through the `dpqueries` config option (and associated budget option); however, historically, the DAS has treated the "detailed query" (or "histogram query", as it is sometimes called in the DP literature; i.e., the query which estimates a scalar value for every possible record type in the current histogram) separately, because of its unique role in determining the size of DAS problems. The configuration file setup reflects this: `detailed` is assumed to always be included in `dpqueries`, and `detailedprop = 0.1` indicates that's 10% of the total `epsilon` is to be spent on the `detailed` query. (Notice that `1 - (.2 + .5 + 0.05 + 0.05 + 0.05 + 0.05) = 0.9`, i.e., the allocation of the budget to the `dpqueries` left 10% of the budget remaining to be allocated to the `detailed` query.)

_Noisy measurements_ are the values of raw private data with DP noise applied to them. The term comes from analogy to a physical measurement of a quantum or thermal system, which yields a result subject to random noise. In a physical system, the precise value is not possible to obtain, either because of thermal fluctuations, or because of quantum non-determinism. Likewise, in privacy context, the private data cannot be accessed directly, only via a measurement, with each measurement consuming privacy budget.
