### ISSUE TITLE
How to understand the L1 metric?

### ISSUE THREAD

**Issue by pwayner** [uscensusbureau/census2020-das-2010ddp#2]
Thank you for posting such a wonderful collection of code for exploring the effects of differential privacy algorithms on census data. I'm trying to understand what is captured by the L1 metric that is applied to compare the post-processed data with the incoming data. There is some pretty good documentation in programs/validation.py but I wanted to ask these questions to make sure I'm understanding it as well as I can. 

TIA....

-  What is compared with the L1 metric? Histograms for each block? 
- What does it mean to move a person from one cell to another? Is the cell one of the bins of a histogram? 
-  Does a reading of .04 mean that 2% of the people were moved from one cell to another? Or is it 4%?
-  Does a reading of 1.0 mean EVERYONE has moved, somehow? 
-  Can movement cancel out? So people are moved and yet the L1 distance is zero? 
-  Is a low L1 number intrinsically better? Why?

**Comment by simsongcensus** [comment]
Thank you for your questions. These questions actually seems to be about the e2e release, as `programs/validator.py` does not appear in this release. It can be found at https://github.com/uscensusbureau/census2020-das-e2e/blob/master/programs/validator.py

We will answer the questions here.

Q: What is compared with the L1 metric? Histograms for each block? 

A: The L1 error estimated in validator.py is the sum-total over all histograms in all blocks: for the entire nation, it returns a single scalar value (a single number), `\sum_{b in Blocks} L1(CEF_b, MDF_b)`, where `L1(CEF_b, MDF_b)` is the usual L1 error between the CEF and MDF counts for block b. Its purpose is to serve as a sanity check, to ensure the security of the system: for any non-trivial total privacy-loss budget, at least one histogram count should be incorrect in at least one block, and so total L1 error nation-wide at the block level, when measured using a DP primitive, should be confidently distinguishable from 0.

Note that this use of the L1 error is somewhat different from our use of the L1 error in summaries of the privacy-accuracy trade-off on the 2010 CEF. In those analyses, which are run using a different (not yet publicly released) set of python/spark modules to compare the CEF to the MDF and generate accuracy summaries, no DP noise was infused into the L1 errors used for presentations that members of the DAS team have made about TopDown's privacy-accuracy trade-off (unlike with the use of the L1 error in validator.py, which infuses DP noise because it is expected to run as a simple but privacy-expensed "sanity check" in the TopDown algorithm's eventual production run)

Q: What does it mean to move a person from one cell to another? Is the cell one of the bins of a histogram? 

A: Importantly, TopDown does not literally move individual records between histogram cells (TopDown's primary representation of data is as a histogram of counts of records of different types, not as microdata), but for any geographic unit with a total-population invariant (without such an invariant, the situation is more complicated), TopDown's effect on the histogram of record counts can be thought of as equivalent to moving some records from their 'true' histogram cell(s) to some other histogram cell(s) within that geographic unit. In this case, yes, we sometimes refer to each bin / index in the geographic unit's corresponding histogram as a 'cell'.

Q: Does a reading of .04 mean that 2% of the people were moved from one cell to another? Or is it 4%?

A: DAS team members have often summarized accuracy/error results using 1 - TVD(G), where G is a set of geographic units with known (invariant) total population N. When 1 - TVD(G) = 0.04, we are in a situation that is equivalent to 'moving' 96% of records from their true histogram cells into incorrect histogram cells (while at the same time never making moving that will 'cancel out' other record-moves). When 1 - TVD(G) = 0.96, we are in a situation that is equivalent to 'moving' 4% of records from their true histogram cells into incorrect histogram cells (and never making off-setting 'record moves' that 'cancel' with these in any way).

Q: Does a reading of 1.0 mean EVERYONE has moved, somehow? 

A: In the 1 - TVD metric, a value of 1.0 corresponds roughly to 'no record has moved to an incorrect histogram cell', while a value of 0.0 could be roughly interpreted as 'every record has been moved to an incorrect histogram cell' (which would be the expected behavior if, for example, there were no invariants except the national total population, and the total privacy-loss budget were set to be arbitrarily close to 0). Note that incorrect in this context refers to any attribute of the record being incorrect; the 1 - TVD metric does not correspond to assigning 'partial credit' for getting most of the attributes in a record right, nor for getting a record's age approximately correct -- when using the 1 - TVD metric, these situations are all treated as equally incorrect.

Q: Can movement cancel out? So people are moved and yet the L1 distance is zero? 

A: 'Movement' is just an analogy, for getting a sense of the scale of change in the 1 - TVD error metric. It is important to keep in mind that individual data records are not manipulated (nor even represented) within the TopDown algorithm. TopDown instead deals only in histogram counts (counts of records of each type), and it is these histogram counts that are changed. 

However, any choice of counts of records of each possible type -- any histogram -- is equivalent to a set of microdata (the microdata set in which, for record type r with histogram count H_r, the microdata set contains H_r-many records with characteristics corresponding to record type r). Because of this property, if the total population of a geographic unit is invariant, then we can think of TVD as measuring "the minimal proportion of records that would need to be changed in order to yield the observed L1 error in the corresponding histogram of counts". This property is the reason that the "moving records between histogram cells" analogy can be used, and is useful for gaining some intuition (so long as its limitations are kept in mind).

In this record-level analogy, it is in fact the case that movement can, in principle, "cancel out". Changing one record from record type/bin i to record type/bin j, and some other record of type/bin j to type/bin i, is a pair of 'record moves' that is neutral with respect to L1 error. However, these "L1-neutral move-pairs" also have no effect on the final tabulations, so they are not interesting from the perspective of evaluating TopDown's accuracy. The tabulations are fully determined by the histogram counts, because the histogram contains all possible record types: if a set of 'moves' does not alter the histogram counts, then it cannot alter the final tabulations.

Q: Is a low L1 number intrinsically better? Why?

A: A low L1 error is better for accuracy than a high L1 error, all else equal, yes. Low total L1 corresponds, roughly, to lower on-average error in individual queries or tabulations of interest. In particular, total histogram L1 error of 0 implies 0 error (of L1 type, or of any other type) in any query, because the histogram exhaustively partitions all possible record types. Very large L1 error, on the other hand, does not necessarily imply that all queries or tabulations will have high error, but it will typically be the case that most queries or tabulations will have poor accuracy when L1 error is large.

**Comment by pwayner** [comment]
These are very helpful answers that add a great deal of illumination. Let me ask another question just to make sure I'm understanding. When I run the default E2E DAS with a the 1940 data (EXT1940USCB.dat ), an epsilon value of 0.2499 split equally between the four lowest levels, the validator.py produces the sentence   "The protected relative total L1 error is 0.07 (above 0.07 with 90% confidence)". 

Should this be interpreted to be 1-TVD and that 93% of the people have changed positions in the histograms because their records have changed? Do that many change?

**Comment by garfi303** [comment]
This is from the team:

"The source of the printed text is the DAS validator: https://github.com/uscensusbureau/census2020-das-e2e/blob/d9faabf3de987b890a5079b914f5aba597215b14/programs/validator.py#L136. The purpose of this module is to validate (in a privacy-protecting way, i.e., using a differentially private query) that the DAS did in fact introduce non-zero noise in generating the MDF from CEF; the goal of this check is to ensure that nothing catastrophic occurred which might cause the DAS to fail to perform its intended purpose. (Strictly speaking, it is possible that the DAS could behave correctly and yet infuse 0 noise when generating the MDF; however, this possibility is so improbable for small-to-modest values of epsilon that the DAS development team felt it appropriate to try to detect this as a failure case.)

Per line 132 in that same module, the quantity printed in this message is a point estimate (with one-sided hypothesis test) of the L1 error normalized by 2N: rL1 = dp_L1 / 2. / N. That means that this value should not be interpreted as an estimate of 1-TVD, but as an estimate of TVD---it is only the error component of 1-TVD, because error (rather than accuracy) is the purpose of this check in the validator. The interpretation proposed in the question should be reversed: an estimated normalized/relative L1 error of 0.07 suggests that, at the lowest level of geographic detail, about 7% of records have changed from their original values."
